name: PR Comment Action
branding:
  icon: arrow-right-circle
  color: gray-dark
description: |
  This action comments on PR

inputs:
  debug-mode:
    description: Set to true for verbose execution when debugging
    required: false
    default: 'false'
  log-level:
    description: The log level to use for the execution
    required: false
    default: 'info'
  log-timestamped:
    description: Set to true in order to enable timestamps on log messages
    required: false
    default: 'true'
  pr-number:
    description: The current pull request number
    required: true
  comment-message:
    description: The comment to post on the PR
    required: true
  unique-comment-id:
    description: The unique id to use for the comment
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup
      shell: bash
      id: setup
      run: |
        echo "scripts-path=${GITHUB_ACTION_PATH}" >>"${GITHUB_OUTPUT}"
    - name: PR Comment
      run: '${{ steps.setup.outputs.scripts-path }}/scripts/script.sh'
      shell: bash
      env:
        DEBUG_MODE: ${{ inputs.debug-mode }}
        LOG_LEVEL: ${{ inputs.log-level }}
        LOG_TIMESTAMPED: ${{ inputs.log-timestamped }}
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMENT_MESSAGE: ${{ inputs.comment-message }}
        UNIQUE_COMMENT_ID: ${{ inputs.unique-comment-id }}
