name: Pre-Commit

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - ready_for_review

jobs:
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
